[pytest]
# Directorio raíz de los tests
testpaths = tests

# Muestra los prints y logs durante la ejecución
log_cli = false

# Variables de entorno para que Flask no cargue .env de producción
# y use siempre la configuración in-memory definida en conftest.py
filterwarnings =
    ignore::DeprecationWarning
