"""add rotation patterns absences tables

Revision ID: 187a551cc921
Revises: 435863985fa2
Create Date: 2026-08-07 11:52:41.691137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '187a551cc921'
down_revision = '435863985fa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('absence_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('short_name', sa.String(length=5), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('counts_as_worked', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rotation_pattern',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cycle_days', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('absence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cleaner_id', sa.Integer(), nullable=False),
    sa.Column('absence_type_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['absence_type_id'], ['absence_type.id'], ),
    sa.ForeignKeyConstraint(['cleaner_id'], ['cleaner.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['cleaner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rotation_pattern_day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern_id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('shift_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pattern_id'], ['rotation_pattern.id'], ),
    sa.ForeignKeyConstraint(['shift_type_id'], ['shift_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pattern_id', 'day_number', name='uq_pattern_day')
    )
    op.create_table('worker_shift_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cleaner_id', sa.Integer(), nullable=False),
    sa.Column('pattern_id', sa.Integer(), nullable=True),
    sa.Column('fixed_shift_type_id', sa.Integer(), nullable=True),
    sa.Column('cycle_start_date', sa.Date(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_until', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cleaner_id'], ['cleaner.id'], ),
    sa.ForeignKeyConstraint(['fixed_shift_type_id'], ['shift_type.id'], ),
    sa.ForeignKeyConstraint(['pattern_id'], ['rotation_pattern.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worker_shift_config')
    op.drop_table('rotation_pattern_day')
    op.drop_table('absence')
    op.drop_table('rotation_pattern')
    op.drop_table('absence_type')
    # ### end Alembic commands ###
