"""add medication tables

Revision ID: 2637f116a157
Revises: 50e7a7f80ad2
Create Date: 2026-08-11 12:39:32.443388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2637f116a157'
down_revision = '50e7a7f80ad2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medication_prescription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resident_id', sa.Integer(), nullable=False),
    sa.Column('drug_name', sa.String(length=150), nullable=False),
    sa.Column('dose', sa.String(length=100), nullable=False),
    sa.Column('route', sa.String(length=50), nullable=True),
    sa.Column('frequency', sa.String(length=50), nullable=False),
    sa.Column('schedule_times', sa.String(length=200), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('prescribed_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['cleaner.id'], ),
    sa.ForeignKeyConstraint(['resident_id'], ['resident.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medication_prescription', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medication_prescription_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_medication_prescription_resident_id'), ['resident_id'], unique=False)

    op.create_table('medication_administration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prescription_id', sa.Integer(), nullable=False),
    sa.Column('administered_at', sa.DateTime(), nullable=True),
    sa.Column('administered_by', sa.Integer(), nullable=False),
    sa.Column('scheduled_time', sa.String(length=5), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['administered_by'], ['cleaner.id'], ),
    sa.ForeignKeyConstraint(['prescription_id'], ['medication_prescription.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medication_administration', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medication_administration_administered_at'), ['administered_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_medication_administration_prescription_id'), ['prescription_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medication_administration', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medication_administration_prescription_id'))
        batch_op.drop_index(batch_op.f('ix_medication_administration_administered_at'))

    op.drop_table('medication_administration')
    with op.batch_alter_table('medication_prescription', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medication_prescription_resident_id'))
        batch_op.drop_index(batch_op.f('ix_medication_prescription_active'))

    op.drop_table('medication_prescription')
    # ### end Alembic commands ###
