"""add daily_cleaning_assignment

Revision ID: 321a30c20508
Revises: fc10d7d2195e
Create Date: 2026-08-11 09:05:53.091914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '321a30c20508'
down_revision = 'fc10d7d2195e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_cleaning_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cleaner_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cleaner_id'], ['cleaner.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['cleaner.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cleaner_id', 'room_id', 'date', name='uq_daily_clean')
    )
    with op.batch_alter_table('daily_cleaning_assignment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_cleaning_assignment_cleaner_id'), ['cleaner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_cleaning_assignment_date'), ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_cleaning_assignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_cleaning_assignment_date'))
        batch_op.drop_index(batch_op.f('ix_daily_cleaning_assignment_cleaner_id'))

    op.drop_table('daily_cleaning_assignment')
    # ### end Alembic commands ###
