"""add shift_coverage_requirement table

Revision ID: 33c1334dafa8
Revises: 187a551cc921
Create Date: 2026-08-07 14:11:44.728556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33c1334dafa8'
down_revision = '187a551cc921'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_coverage_requirement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shift_type_id', sa.Integer(), nullable=False),
    sa.Column('day_type', sa.String(length=20), nullable=True),
    sa.Column('min_workers', sa.Integer(), nullable=False),
    sa.Column('ideal_workers', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shift_type_id'], ['shift_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shift_type_id', 'day_type', name='uq_coverage_shift_day')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shift_coverage_requirement')
    # ### end Alembic commands ###
