"""add shift_type and shift_assignment tables

Revision ID: 435863985fa2
Revises: 9fb1fa2626a1
Create Date: 2026-08-07 11:07:55.304882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '435863985fa2'
down_revision = '9fb1fa2626a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('short_name', sa.String(length=5), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('breaks_minutes', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('shift_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cleaner_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('shift_type_id', sa.Integer(), nullable=True),
    sa.Column('is_override', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cleaner_id'], ['cleaner.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['cleaner.id'], ),
    sa.ForeignKeyConstraint(['shift_type_id'], ['shift_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cleaner_id', 'date', name='uq_worker_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shift_assignment')
    op.drop_table('shift_type')
    # ### end Alembic commands ###
