"""add assessment_record weight_record meal_intake_record

Revision ID: 50e7a7f80ad2
Revises: 321a30c20508
Create Date: 2026-08-11 10:08:00.420283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50e7a7f80ad2'
down_revision = '321a30c20508'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resident_id', sa.Integer(), nullable=False),
    sa.Column('scale_type', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('interpretation', sa.String(length=50), nullable=True),
    sa.Column('answers_json', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('assessed_by', sa.Integer(), nullable=True),
    sa.Column('assessed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessed_by'], ['cleaner.id'], ),
    sa.ForeignKeyConstraint(['resident_id'], ['resident.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_record_assessed_at'), ['assessed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_record_resident_id'), ['resident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_record_scale_type'), ['scale_type'], unique=False)

    op.create_table('meal_intake_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resident_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.String(length=20), nullable=False),
    sa.Column('intake_pct', sa.Integer(), nullable=False),
    sa.Column('fluid_ml', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recorded_by'], ['cleaner.id'], ),
    sa.ForeignKeyConstraint(['resident_id'], ['resident.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resident_id', 'date', 'meal_type', name='uq_meal_intake')
    )
    with op.batch_alter_table('meal_intake_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_intake_record_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_intake_record_resident_id'), ['resident_id'], unique=False)

    op.create_table('weight_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resident_id', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('recorded_by', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['recorded_by'], ['cleaner.id'], ),
    sa.ForeignKeyConstraint(['resident_id'], ['resident.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weight_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weight_record_recorded_at'), ['recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_weight_record_resident_id'), ['resident_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weight_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weight_record_resident_id'))
        batch_op.drop_index(batch_op.f('ix_weight_record_recorded_at'))

    op.drop_table('weight_record')
    with op.batch_alter_table('meal_intake_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_intake_record_resident_id'))
        batch_op.drop_index(batch_op.f('ix_meal_intake_record_date'))

    op.drop_table('meal_intake_record')
    with op.batch_alter_table('assessment_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_record_scale_type'))
        batch_op.drop_index(batch_op.f('ix_assessment_record_resident_id'))
        batch_op.drop_index(batch_op.f('ix_assessment_record_assessed_at'))

    op.drop_table('assessment_record')
    # ### end Alembic commands ###
