"""add activity and activity_participation

Revision ID: 7b4bc27b2918
Revises: 2637f116a157
Create Date: 2026-08-11 15:20:42.155516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b4bc27b2918'
down_revision = '2637f116a157'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['cleaner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_activity_date'), ['activity_date'], unique=False)

    op.create_table('activity_participation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('resident_id', sa.Integer(), nullable=False),
    sa.Column('engagement', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['resident_id'], ['resident.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', 'resident_id', name='uq_activity_resident')
    )
    with op.batch_alter_table('activity_participation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_participation_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_participation_resident_id'), ['resident_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('activity_participation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_participation_resident_id'))
        batch_op.drop_index(batch_op.f('ix_activity_participation_activity_id'))

    op.drop_table('activity_participation')
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_activity_date'))

    op.drop_table('activity')
    # ### end Alembic commands ###
