"""empty message

Revision ID: 8adeefd92ca9
Revises: 
Create Date: 2023-12-08 09:59:18.852224

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8adeefd92ca9'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('floor_id', sa.Integer(), nullable=False))
        # Añade un nombre a la restricción de clave foránea
        batch_op.create_foreign_key('fk_room_floor_id', 'floor', ['floor_id'], ['id'])

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        # Usa el mismo nombre para eliminar la restricción
        batch_op.drop_constraint('fk_room_floor_id', type_='foreignkey')
        batch_op.drop_column('floor_id')
    # ### end Alembic commands ###
