"""add identity, documents and training models

Revision ID: fb8d2aa0a90f
Revises: e5f6a7b8c9d0
Create Date: 2026-07-15 23:35:28.686315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb8d2aa0a90f'
down_revision = 'e5f6a7b8c9d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legal_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['cleaner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_pill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('video_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('pass_threshold', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['cleaner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worker_selfie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cleaner_id', sa.Integer(), nullable=False),
    sa.Column('photo_path', sa.String(length=255), nullable=False),
    sa.Column('is_reference', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('purpose', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['cleaner_id'], ['cleaner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_signature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('cleaner_id', sa.Integer(), nullable=False),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('selfie_path', sa.String(length=255), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['cleaner_id'], ['cleaner.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['legal_document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_completion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pill_id', sa.Integer(), nullable=False),
    sa.Column('cleaner_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('answers_json', sa.Text(), nullable=True),
    sa.Column('video_watched', sa.Boolean(), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('shuffle_map', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cleaner_id'], ['cleaner.id'], ),
    sa.ForeignKeyConstraint(['pill_id'], ['training_pill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pill_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.String(length=500), nullable=False),
    sa.Column('option_a', sa.String(length=200), nullable=False),
    sa.Column('option_b', sa.String(length=200), nullable=False),
    sa.Column('option_c', sa.String(length=200), nullable=False),
    sa.Column('option_d', sa.String(length=200), nullable=False),
    sa.Column('correct_option', sa.String(length=1), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pill_id'], ['training_pill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cleaner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identity_verified', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cleaner', schema=None) as batch_op:
        batch_op.drop_column('identity_verified')

    op.drop_table('training_question')
    op.drop_table('training_completion')
    op.drop_table('document_signature')
    op.drop_table('worker_selfie')
    op.drop_table('training_pill')
    op.drop_table('legal_document')
    # ### end Alembic commands ###
